grade_patterns:
  - 'grade\s*(\d+)'
  - 'class\s*(\d+)'
  - 'year\s*(\d+)'

grade_levels:
  grade: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Add LLM context to YAML
llm_context:
  grade_examples: ["grade 4", "grade 10", "grade 4-6"]
  range_examples: ["Grade 4-6", "Grade 10-12"]
  sample_topics: ["numbers", "algebra", "geometry"]

inference_keywords:
  grade: ['grade', 'class', 'year']

number_ranges:
  grade: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

subjects:
  - mathematics
  - english
  - afrikaans
  - natural_sciences
  - social_sciences
  - life_orientation

# South African exam patterns
exam_patterns:
  quiz:
    weeks_covered: [1, 2]
    duration: "30 minutes"
    total_marks: 25
    description: "Informal Assessment"
  
  mid_term:
    weeks_covered: [1, 2, 3, 4, 5, 6]
    duration: "2 hours"
    total_marks: 75
    description: "June Examination"
  
  end_of_term:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    duration: "3 hours"
    total_marks: 100
    description: "November Examination"
  
  final_exam:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    duration: "3 hours"
    total_marks: 100
    description: "National Senior Certificate (NSC) Examination"
