grade_patterns:
  - 'class\s*level\s*:\s*(primary|secondary|jss|sss)\s*(\d+)'
  - '(primary|secondary|jss|sss)\s*(\d+)'
  - 'grade\s*(\d+)'
  - 'year\s*(\d+)'

# Add LLM context to YAML
llm_context:
  grade_examples: ["primary 4", "jss 2", "sss 1", "primary 4-6"]
  range_examples: ["Primary 4-6", "JSS 1-3"]
  sample_topics: ["numbers", "algebra", "geometry"]

inference_keywords:
  primary: ['primary', 'elementary']
  secondary: ['secondary', 'jss', 'sss']

subjects:
  - mathematics
  - english
  - basic_science
  - civic_education
  - social_studies

# Nigerian exam patterns
exam_patterns:
  quiz:
    weeks_covered: [1, 2]
    duration: "30 minutes"
    total_marks: 20
    description: "Class Test"
  
  mid_term:
    weeks_covered: [1, 2, 3, 4, 5, 6]
    duration: "1.5 hours"
    total_marks: 50
    description: "Mid-Term Examination"
  
  end_of_term:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    duration: "2 hours"
    total_marks: 100
    description: "End of Term Examination"
  
  final_exam:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    duration: "3 hours"
    total_marks: 100
    description: "Annual Examination"
