grade_patterns:
  - '(primary|jhs|shs)\s*(\d+)'
  - 'class\s*(\d+)'
  - 'grade\s*(\d+)'
  - 'year\s*(\d+)'

grade_levels:
  primary: [1, 2, 3, 4, 5, 6]
  jhs: [1, 2, 3]
  shs: [1, 2, 3]

# Add LLM context to YAML
llm_context:
  grade_examples: ["primary 4", "jhs 2", "shs 1", "primary 4-6"]
  range_examples: ["Primary 4-6", "JHS 1-3"]
  sample_topics: ["numbers", "algebra", "geometry"]

inference_keywords:
  primary: ['primary', 'elementary']
  jhs: ['jhs', 'junior high', 'junior']
  shs: ['shs', 'senior high', 'senior']

number_ranges:
  primary: [1, 2, 3, 4, 5, 6]
  jhs: [7, 8, 9]
  shs: [10, 11, 12]

subjects:
  - mathematics
  - english
  - integrated_science
  - social_studies
  - religious_moral_education
  - creative_arts

# Ghanaian exam patterns  
exam_patterns:
  quiz:
    weeks_covered: [1, 2]
    duration: "45 minutes"
    total_marks: 25
    description: "Class Assessment"
  
  mid_term:
    weeks_covered: [1, 2, 3, 4, 5, 6]
    duration: "2 hours"
    total_marks: 60
    description: "Mid-Semester Examination"
  
  end_of_term:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    duration: "2.5 hours"
    total_marks: 100
    description: "End of Semester Examination"
  
  final_exam:
    weeks_covered: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    duration: "3 hours"
    total_marks: 100
    description: "Annual Examination"
